version: '3.8'

services:
  api:
    build: .
    container_name: tennis_api
    ports:
      - "80:8000"
    volumes:
      - ./src:/api
    env_file:
      - .env/api.env
      - .env/db.env
    command: /bin/sh -c "pipenv run python manage.py migrate && pipenv run python manage.py collectstatic --no-input && pipenv run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
  
  # worker:
  #   build: .
  #   container_name: tennis_worker
  #   volumes:
  #     - ./src:/api
  #   env_file:
  #     - .env/api.env
  #     - .env/db.env
  #   command: /bin/sh -c "celery -A tennis worker --loglevel INFO"
  #   depends_on:
  #     - api
  #     - db
  #     - redis
  
  db:
    image: postgres:14-bullseye
    container_name: tennis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/db.env
  
  redis:
    image: redis:6.2-bullseye
    container_name: tennis_redis

volumes:
  postgres_data:
    