# Generated by Django 4.2 on 2024-04-20 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='courts.court')),
            ],
        ),
    ]
